# Generated by Django 2.0 on 2018-12-11 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lkModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('request_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='lkModelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='lkmodel',
            name='model_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lkwebapp.lkModelType'),
        ),
    ]
